### ISSUE TITLE
Creación de rol - Estructura HTML + Estilos Css

### ISSUE THREAD

**Issue by acem0301** [acem0301/frontis2#10]
Tarea:
-Realizar una vista que sirva para crear un rol, aplicando la estructura Html y los estilos Css correspondientes.
-Agregar un select list al formulario en dónde se mostrarán permisos predefinidos. Para este select list se puede utilizar Vue-Multiselect o hacerlo con html.
Obs: La imagen que se encuentra abajo es a modo de ejemplo, la estructura sería similar, utilizando los campos correspondientes a Rol , los estilos Css serían similares a lo que ya realizó César con el menú lateral.

**Comment by Angatupyry** [comment]
![Screenshot_20200313_212247](https://user-images.githubusercontent.com/37310205/76670759-05214e00-6571-11ea-849f-e26ae87eea1c.png)
