### ISSUE TITLE
Listar usuarios - Integración con el API

### ISSUE THREAD

**Issue by acem0301** [acem0301/frontis2#13]

**Comment by Angatupyry** [comment]
![Screenshot_20200313_212810](https://user-images.githubusercontent.com/37310205/76670854-9c86a100-6571-11ea-9688-e5d457ebff23.png)

**Comment by acem0301** [comment]
Tarea: 
-Realizar una vista que traiga una lista de usuarios, aplicando la estructura Html y los estilos Css correspondientes. 
-Agregar botones de edición y eliminación de ítem a cada elemento de la lista.
Obs: La imagen que se encuentra arriba es a modo de ejemplo, la estructura sería similar, utilizando los mismos campos, los estilos Css serían similares a lo que ya realizó César con el menú lateral.
