### ISSUE TITLE
Creación de rol -Integración con el API

### ISSUE THREAD

**Issue by acem0301** [acem0301/frontis2#14]
Tarea: 
-Se debe agregar el código correspondiente para poder conectar esta vista a un endpoint o ruta proveniente del backend que traiga reciba los datos de este formulario y los almacene.

**Comment by acem0301** [comment]
![Screenshot_20200313_212247](https://user-images.githubusercontent.com/37310205/76670759-05214e00-6571-11ea-849f-e26ae87eea1c.png)

**Comment by Angatupyry** [comment]
Falta que impacte a la tabla rol_permiso. 
Por ahora solo se guarda el rol con su descripción.
