### ISSUE TITLE
Los ítems que han sido cerrados no podrán ser editados. Solo se pueden ver.

### ISSUE THREAD

**Issue by acem0301** [acem0301/frontis2#40]
Deshabilitar u ocultar botón de editar de la tarea que haya pasado al estado "Cerrado".

**Comment by Angatupyry** [comment]
Hecho.
Faltaría agregar un ícono en donde se pueda ver pero sin editar ningún dato.
Eso para que el usuario tenga mejor visualización del ítem porque en la lista no puede ser bien controlado.
